
export const codebookData = [
    { Variable: 'participant_id', Label: 'Participant Identifier', Type: 'String', ScoringRule: 'Unique alphanumeric ID assigned by platform', MissingnessRule: 'Never missing (required)' },
    { Variable: 'random_seed', Label: 'RNG Seed', Type: 'String', ScoringRule: 'Seed used for randomization (logged)', MissingnessRule: 'Retain; not used in analysis' },
    { Variable: 'start_time', Label: 'Session start timestamp', Type: 'Datetime', ScoringRule: 'ISO-8601 timestamp', MissingnessRule: 'If missing, flag for logging issues' },
    { Variable: 'device_type', Label: 'Device used', Type: 'Categorical', ScoringRule: 'Desktop / Mobile / Tablet', MissingnessRule: 'If missing, report but keep in models if available' },
    { Variable: 'advisory_view_time', Label: 'Advisory viewing time (s)', Type: 'Numeric', ScoringRule: 'Seconds displayed; recorded from page load to next page', MissingnessRule: 'If <0 or missing, flag; used in sensitivity checks' },
    { Variable: 'comp_org', Label: 'Comprehension: org name', Type: 'Binary', ScoringRule: '1 = correct; 0 = incorrect', MissingnessRule: 'If missing, treated as incorrect for sensitivity flags' },
    { Variable: 'comp_horizon', Label: 'Comprehension: time horizon', Type: 'Binary', ScoringRule: '1 = correct; 0 = incorrect', MissingnessRule: 'If missing, treated as incorrect for sensitivity flags' },
    { Variable: 'man_algo', Label: 'Perceived algorithmic origin', Type: 'Scale', ScoringRule: '1-7 Likert (1=not at all...7=very much)', MissingnessRule: 'Composite use requires non-missing' },
    { Variable: 'man_whodoneit', Label: 'Forced-choice belief about source', Type: 'Categorical', ScoringRule: '1=AI; 2=Human; 3=Unsure', MissingnessRule: 'If missing, record as NA' },
    { Variable: 'choice_code', Label: 'Objective choice code', Type: 'Categorical', ScoringRule: 'Numeric code mapping options A/B/C; normative = C', MissingnessRule: 'If missing, exclude from OBJ_DQ analyses' },
    { Variable: 'dq1...dq4', Label: 'Subjective DQ items', Type: 'Scale', ScoringRule: 'Four 7-point Likert items', MissingnessRule: 'N/A' },
    { Variable: 'DQ_SUB_MEAN', Label: 'Subjective DQ Composite', Type: 'Numeric', ScoringRule: 'Mean(DQ1-DQ4)', MissingnessRule: 'Compute mean if >=75% items present; otherwise missing' },
    { Variable: 'cr_trust1...3', Label: 'Credibility - trust items', Type: 'Scale', ScoringRule: 'Three 7-point items', MissingnessRule: 'N/A' },
    { Variable: 'CR_TRUST', Label: 'Credibility - Trust Composite', Type: 'Numeric', ScoringRule: 'Mean(cr_trust1..3)', MissingnessRule: 'Subscale mean if >=75% present' },
    { Variable: 'cr_good1...3', Label: 'Credibility - goodwill items', Type: 'Scale', ScoringRule: 'Three 7-point items', MissingnessRule: 'N/A' },
    { Variable: 'CR_GOOD', Label: 'Credibility - Goodwill Composite', Type: 'Numeric', ScoringRule: 'Mean(cr_good1..3)', MissingnessRule: 'Subscale mean if >=75% present' },
    { Variable: 'cr_comp1...3', Label: 'Credibility - competence items', Type: 'Scale', ScoringRule: 'Three 7-point items', MissingnessRule: 'N/A' },
    { Variable: 'CR_COMP', Label: 'Credibility - Competence Composite', Type: 'Numeric', ScoringRule: 'Mean(cr_comp1..3)', MissingnessRule: 'Subscale mean if >=75% present' },
    { Variable: 'CR_GLOBAL_MEAN', Label: 'Credibility - Global Composite', Type: 'Numeric', ScoringRule: 'Mean(CR_TRUST, CR_GOOD, CR_COMP)', MissingnessRule: 'Mean of available, non-missing subscales' },
    { Variable: 'pd_temp/soc/spat/hyp', Label: 'Psychological distance items', Type: 'Scale', ScoringRule: 'Four 7-point items', MissingnessRule: 'N/A' },
    { Variable: 'PD_COMPOSITE', Label: 'Psychological Distance Composite', Type: 'Numeric', ScoringRule: 'Mean(pd_temp, pd_soc, pd_spat, pd_hyp)', MissingnessRule: 'Composite if >=75% items present' },
    { Variable: 'la1...la4', Label: 'Perceived linguistic abstractness items', Type: 'Scale', ScoringRule: 'Four 7-point items', MissingnessRule: 'N/A' },
    { Variable: 'LA_PERCEIVED', Label: 'Perceived Linguistic Abstractness Composite', Type: 'Numeric', ScoringRule: 'Mean(la1..4)', MissingnessRule: 'Composite if >=75% items present' },
    { Variable: 'la_objective', Label: 'Objective linguistic abstractness score', Type: 'Numeric', ScoringRule: 'Computed via LA pipeline; not z-scored', MissingnessRule: 'May be missing if pipeline fails' },
    { Variable: 'finlit1...4', Label: 'Financial literacy quiz items', Type: 'Binary', ScoringRule: 'Each scored 1=correct; 0=incorrect', MissingnessRule: 'N/A' },
    { Variable: 'FINLIT_SUM', Label: 'Financial Literacy Composite', Type: 'Numeric', ScoringRule: 'Sum(finlit1..4)', MissingnessRule: 'Computed if >=3 items present' },
    { Variable: 'risk_f1...5', Label: 'DOSPERT finance items', Type: 'Scale', ScoringRule: 'Five 1-7 items; risk_f5 reversed before composite', MissingnessRule: 'N/A' },
    { Variable: 'RISK_F_COMPOSITE', Label: 'Risk Tolerance Composite', Type: 'Numeric', ScoringRule: 'Mean of risk_f items after reverse coding', MissingnessRule: 'Missing if <75% present' },
    { Variable: 'choice_reason_text', Label: 'Open rationale', Type: 'String', ScoringRule: 'Participant free-text for decision rationale', MissingnessRule: 'Free text redacted for PII before release' },
    { Variable: 'flag_comprehension', Label: 'Flag: comprehension failure', Type: 'Binary', ScoringRule: '1 if both comp_org AND comp_horizon are incorrect (0)', MissingnessRule: 'Used for sensitivity exclusions' },
    { Variable: 'flag_viewtime', Label: 'Flag: minimal exposure', Type: 'Binary', ScoringRule: '1 if dossier_view_time + advisory_view_time < 10s', MissingnessRule: 'Used for sensitivity exclusions' },
    { Variable: 'flag_straightline', Label: 'Flag: straight-lining', Type: 'Binary', ScoringRule: '1 if >=80% of responses in a single matrix are the same', MissingnessRule: 'Used for sensitivity exclusions' },
    { Variable: 'flagged_any', Label: 'Any exclusion flag', Type: 'Binary', ScoringRule: '1 if any flag_comprehension OR flag_viewtime OR flag_straightline = 1', MissingnessRule: 'Not used in primary analysis; for robustness' },
];
