
'use client';

import type { SessionData } from '@/lib/types';
import { BrainCircuit, User } from 'lucide-react';

type StepProps = {
    sessionData: Partial<SessionData>;
};

const advisoryContent = {
    human: {
        title: "Human Organizational Advisory",
        logo: <User className="h-8 w-8 text-primary" />,
        intro: "This advisory brief was prepared by a licensed human organizational financial advisor with 15 years’ professional experience in corporate treasury advisory.",
        preparedBy: "John Michaels, CFA — Senior Financial Advisor."
    },
    ai: {
        title: "AI-Generated Organizational Advisory",
        logo: <BrainCircuit className="h-8 w-8 text-primary" />,
        intro: "This advisory brief was generated by an automated AI advisory system trained on aggregated anonymized financial data and governance guidelines: model transparency log available.",
        preparedBy: "AIFinAd v2.1 — An Automated Financial Advisory System."
    }
};

const scenarioContent = {
    xyz: {
        to: "Financial Decision-Makers, XYZ Manufacturing",
        from: "John Michaels, CFA — Senior Financial Advisor",
        subject: "Recommended Allocation: $1,000,000 Surplus Funds",
        executiveSummary: "Given the board’s high-priority directive to prioritize capital preservation, liquidity, and alignment with planned operational investments (notably the IoT product launch within a two-year horizon), the recommended allocation for the $1,000,000 surplus is: 100% to Option C — Government Bonds. This recommendation balances the firm’s stated mandates and the need to keep strategic funds accessible and secure.",
        analyticalFramework: "The recommendation was reached by evaluating each option against the board’s weighted priorities: Capital Preservation (0.30), Strategic Alignment (0.25), Liquidity (0.25), Risk Mitigation (0.15), Transparency and ESG (0.05). The consideration input included firm financials (Revenue $50M; Cash Reserves $5M; CapEx $3M), investment characteristics (risk, expected return, volatility), and liquidity needs tied to the 24-month strategic horizon.",
        options: [
            { title: "Option A: Industrial Sector ETFs", text: "High return potential but high volatility and sector concentration risk. Low compliance with capital preservation and liquidity mandates under the stated constraints." },
            { title: "Option B: Diversified Mutual Funds", text: "Moderate returns and medium volatility. It improves diversification but does not guarantee principal and may hinder liquidity in stressed markets." },
            { title: "Option C: Government Bonds", text: "Low nominal return but minimal volatility, high liquidity in secondary markets, and near-certainty of principal preservation for the two-year horizon." }
        ],
        justification: [
            "Mandate compliance scores (weighted): Option A ~ 54, Option B ~ 68, Option C ~ 94",
            "Probability of preserving principal over the two-year horizon: Option A ~ 72%, Option B ~ 85%, Option C ≈100%.",
            "Risk-adjusted metrics favor Option C when capital preservation is the primary objective."
        ],
        implications: [
            "Preserving principal and maintaining liquidity ensures funding is available for planned CapEx and the IoT launch without requiring emergency financing or delaying strategic initiatives.",
            "Choosing higher-yield, higher-volatility options exposes the firm to correlated downside risk given its industry exposure, which could necessitate cost-cutting or deferred investments if realized."
        ],
        recommendation: "Allocate 100% of the $1,000,000 surplus to Option C (Government Bonds). This allocation best satisfies the board’s high-priority constraints and preserves strategic optionality for the firm over the 24-month planning horizon.",
        implementationNotes: [
            "Select short- to intermediate-duration government securities to reduce interest-rate sensitivity consistent with the two-year liquidity preference.",
            "Document the decision rationale and mark the holding as strategic liquidity in treasury records to ensure alignment with governance and audit requirements.",
            "Reassess allocation policy quarterly and prior to any major CapEx drawdown."
        ]
    },
    techtrend: {
        to: "Financial Decision-Makers, TechTrend Innovations",
        from: "John Michaels, CFA — Senior Financial Advisor",
        subject: "Recommended Allocation: $500,000 Surplus Funds",
        executiveSummary: "Given the board’s high-priority directives to preserve runway, support R&D, and maintain operational liquidity through the product launch timeline, the recommended allocation for the $500,000 surplus is: 100% to Option C — Government Bonds. This recommendation prioritizes the survival-critical objective of extending runway and safeguarding funds for product development milestones.",
        analyticalFramework: "The recommendation applies a constrained optimization approach aligning investment options with board priorities: Runway Preservation (0.35), R&D Support (0.25), Path to Profitability (0.20), Ethical Standards and Scalability (0.20). The consideration input included firm finances (Cash Reserves $1M; Monthly Burn ~$100K; Runway ~10 months), investment risk-return profiles, and short-term liquidity requirements.",
        options: [
            { title: "Option A: Industrial Sector ETFs", text: "Highest expected return but substantial volatility and sector correlation risk; presents an unacceptable chance of principal erosion given runway sensitivity." },
            { title: "Option B: Diversified Mutual Funds", text: "Moderate returns and reduced volatility relative to ETFs but still insufficiently guaranteed for runway protection." },
            { title: "Option C: Government Bonds", text: "Lowest volatility, highest probability of principal preservation, and suitable liquidity characteristics for the 18–24-month operational horizon." }
        ],
        justification: [
            "Mandate compliance scores (weighted): Option A ~ 54, Option B ~ 72, Option C ~ 95",
            "Probability of preserving principal over the 18-month horizon: Option A ~ 69%, Option B ~ 85%, Option C ≈100%.",
            "Downside-risk-focused metrics (e.g., Sortino/Value-at-Risk) favor Option C for maintaining runway."
        ],
        implications: [
            "Guaranteeing the availability of funds for R&D and launch activities reduces the need for emergency fundraising or disruptive cost reductions and preserves strategic momentum.",
            "Exposure to sector-wide downside would likely coincide with operational challenges for the firm, amplifying overall business risk."
        ],
        recommendation: "Allocate 100% of the $500,000 surplus to Option C: Government Bonds. This allocation is the most defensible choice given the firm’s immediate liquidity needs and the board’s explicit priority on runway and R&D continuity.",
        implementationNotes: [
            "Favor short-duration government issues or a laddered approach to managing interest-rate exposure while maintaining access to funds.",
            "Record the decision and rationales in governance documents and treasury policies.",
            "Review the allocation prior to key funding milestones or if firm cash-flow projections materially change."
        ]
    }
}

export default function AdvisoryMemo({ sessionData }: StepProps) {
    const { condition } = sessionData;
    if (!condition) return <div className="p-8 text-center">Loading advisory...</div>;

    const sourceData = advisoryContent[condition.advisorySource];
    const scenarioData = scenarioContent[condition.scenario];

    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    return (
        <div className="bg-white text-gray-800 font-serif p-8">
            <header className="pb-4 border-b-2 border-gray-800">
                <div className="flex items-center space-x-4">
                    <div className="flex-shrink-0">
                        {sourceData.logo}
                    </div>
                    <h1 className="text-xl font-bold text-gray-900">{sourceData.title}</h1>
                </div>
                <p className="text-xs text-gray-600 mt-2 italic">{sourceData.intro}</p>
            </header>

            <section className="my-6 text-sm">
                <div className="grid grid-cols-[80px_1fr] gap-x-4 gap-y-1">
                    {condition.advisorySource === 'human' && <>
                        <span className="font-bold">From:</span><span>{scenarioData.from}</span>
                    </>}
                    <span className="font-bold">To:</span><span>{scenarioData.to}</span>
                    <span className="font-bold">Date:</span><span>{today}</span>
                    <span className="font-bold">Subject:</span><span className="font-bold">{scenarioData.subject}</span>
                </div>
            </section>

            <main className="space-y-6 text-sm leading-relaxed">
                <div className="p-4 border rounded-lg">
                    <h2 className="text-base font-bold text-gray-900 mb-2">1.0 Executive Summary</h2>
                    <p>{scenarioData.executiveSummary}</p>
                </div>
                
                <div className="p-4 border rounded-lg">
                    <h2 className="text-base font-bold text-gray-900 mb-2">2.0 Analytical Framework</h2>
                    <p>{scenarioData.analyticalFramework}</p>
                </div>

                <div className="p-4 border rounded-lg">
                    <h2 className="text-base font-bold text-gray-900 mb-2">3.0 Comparative Option Analysis</h2>
                    <div className="space-y-3">
                        {scenarioData.options.map((option, index) => (
                           <div key={index} className="p-3 border rounded-md bg-gray-50/50"><span className="font-bold italic">{option.title}:</span> {option.text}</div>
                        ))}
                    </div>
                </div>

                <div className="p-4 border rounded-lg">
                    <h2 className="text-base font-bold text-gray-900 mb-2">4.0 Recommendation & Strategic Justification</h2>
                     <div className="space-y-2">
                        {scenarioData.justification.map((item, index) => (
                            <div key={index} className="p-3 border rounded-md bg-gray-50/50">{item}</div>
                        ))}
                    </div>
                </div>

                <div className="p-4 border rounded-lg">
                    <h2 className="text-base font-bold text-gray-900 mb-2">5.0 Strategic Implications</h2>
                    <div className="space-y-2">
                        {scenarioData.implications.map((item, index) => (
                            <div key={index} className="p-3 border rounded-md bg-gray-50/50">{item}</div>
                        ))}
                    </div>
                </div>

                <div className="p-4 border rounded-lg">
                    <h2 className="text-base font-bold text-gray-900 mb-2">6.0 Recommendation</h2>
                    <p className="font-bold">{scenarioData.recommendation}</p>
                </div>

                <div className="p-4 border rounded-lg">
                    <h2 className="text-base font-bold text-gray-900 mb-2">7.0 Implementation Notes</h2>
                    <div className="space-y-2">
                        {scenarioData.implementationNotes.map((item, index) => (
                            <div key={index} className="p-3 border rounded-md bg-gray-50/50">{item}</div>
                        ))}
                    </div>
                </div>
            </main>

            <footer className="mt-8 pt-4 border-t border-gray-300 text-xs text-gray-600">
                <p>
                    <span className="font-bold">Prepared by:</span> {sourceData.preparedBy}
                </p>
            </footer>
        </div>
    );
}

    
