
'use client';

import { useForm } from 'react-hook-form';
import { CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Form, FormControl, FormField, FormItem, FormLabel } from '@/components/ui/form';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import type { SessionData } from '@/lib/types';
import { useEffect } from 'react';
import { CheckSquare } from 'lucide-react';

type StepProps = {
  sessionData: Partial<SessionData>;
  updateSessionData: (data: Partial<SessionData>) => void;
};

type FormValues = {
  feltHuman: string;
  feltAlgorithm: string;
  sourceAttribution: string;
};

const likertOptions = [
    'Strongly disagree',
    'Disagree',
    'Somewhat disagree',
    'Neither agree nor disagree',
    'Somewhat agree',
    'Agree',
    'Strongly agree',
];

const sourceOptions = [
    'AI system',
    'Human advisor',
    'Both',
    'I don\'t remember',
]

export default function StepManipulationChecks({ sessionData, updateSessionData }: StepProps) {
  const form = useForm<FormValues>({
    defaultValues: {
      feltHuman: sessionData.manipulationChecks?.feltHuman || '',
      feltAlgorithm: sessionData.manipulationChecks?.feltAlgorithm || '',
      sourceAttribution: sessionData.manipulationChecks?.sourceAttribution || '',
    },
  });

  const { watch } = form;

  useEffect(() => {
    const subscription = watch((value) => {
      updateSessionData({ manipulationChecks: value as Record<string, string> });
    });
    return () => subscription.unsubscribe();
  }, [watch, updateSessionData]);

  return (
    <>
      <CardHeader>
        <div className="flex items-center gap-3">
            <CheckSquare className="h-6 w-6 text-primary" />
            <CardTitle className="font-headline text-2xl">Section D: Manipulation Checks</CardTitle>
        </div>
        <CardDescription>
          Please answer the following questions based on your experience.
        </CardDescription>
      </CardHeader>
      <div className="p-6 pt-0">
        <Form {...form}>
          <form className="space-y-6">
            <FormField
              control={form.control}
              name="feltHuman"
              render={({ field }) => (
                <FormItem className="space-y-3 p-4 border rounded-lg bg-secondary/30">
                  <FormLabel className="font-semibold text-base">a. The source of the advisory felt human.</FormLabel>
                  <FormControl>
                    <RadioGroup onValueChange={field.onChange} value={field.value} className="space-y-2">
                      {likertOptions.map(option => (
                         <Label key={option} htmlFor={`q1-${option}`} className="flex items-center space-x-3 p-2 cursor-pointer has-[:checked]:text-accent transition-colors">
                            <FormControl><RadioGroupItem value={option} id={`q1-${option}`} /></FormControl>
                            <span className="font-normal text-base">{option}</span>
                        </Label>
                      ))}
                    </RadioGroup>
                  </FormControl>
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="feltAlgorithm"
              render={({ field }) => (
                <FormItem className="space-y-3 p-4 border rounded-lg bg-secondary/30">
                  <FormLabel className="font-semibold text-base">b. The source of the advisory felt generated by an algorithm.</FormLabel>
                  <FormControl>
                    <RadioGroup onValueChange={field.onChange} value={field.value} className="space-y-2">
                       {likertOptions.map(option => (
                         <Label key={option} htmlFor={`q2-${option}`} className="flex items-center space-x-3 p-2 cursor-pointer has-[:checked]:text-accent transition-colors">
                            <FormControl><RadioGroupItem value={option} id={`q2-${option}`} /></FormControl>
                            <span className="font-normal text-base">{option}</span>
                        </Label>
                      ))}
                    </RadioGroup>
                  </FormControl>
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="sourceAttribution"
              render={({ field }) => (
                <FormItem className="space-y-3 p-4 border rounded-lg bg-secondary/30">
                  <FormLabel className="font-semibold text-base">c. Who produced the advisory you just read?</FormLabel>
                  <FormControl>
                    <RadioGroup onValueChange={field.onChange} value={field.value} className="space-y-2">
                       {sourceOptions.map(option => (
                         <Label key={option} htmlFor={`q3-${option}`} className="flex items-center space-x-3 p-2 cursor-pointer has-[:checked]:text-accent transition-colors">
                            <FormControl><RadioGroupItem value={option} id={`q3-${option}`} /></FormControl>
                            <span className="font-normal text-base">{option}</span>
                        </Label>
                      ))}
                    </RadioGroup>
                  </FormControl>
                </FormItem>
              )}
            />
          </form>
        </Form>
      </div>
    </>
  );
}
