
'use client';

import type { SessionData } from '@/lib/types';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { useMemo } from 'react';

type DescriptiveStatsProps = {
    sessions: SessionData[] | null;
};

const LIKERT_MAP: Record<string, number> = {
    'Strongly disagree': 1, 'Disagree': 2, 'Somewhat disagree': 3,
    'Neither agree nor disagree': 4, 'Somewhat agree': 5, 'Agree': 6, 'Strongly agree': 7,
};

const calculateFrequency = (data: (string | null | undefined)[]) => {
    const counts: Record<string, { count: number; percentage: string }> = {};
    const total = data.filter(item => item !== null && item !== undefined && item !== '').length;
    if (total === 0) return {};

    data.forEach(item => {
        if (item) {
            counts[item] = counts[item] || { count: 0, percentage: '' };
            counts[item].count++;
        }
    });

    for (const key in counts) {
        counts[key].percentage = ((counts[key].count / total) * 100).toFixed(1) + '%';
    }
    return counts;
};

const calculateMeanStd = (data: (string | null | undefined)[]) => {
    const numericData = data.map(d => d ? LIKERT_MAP[d] : null).filter((d): d is number => d !== null);
    if (numericData.length === 0) return { mean: 'N/A', std: 'N/A' };

    const mean = numericData.reduce((a, b) => a + b, 0) / numericData.length;
    const std = Math.sqrt(numericData.map(x => Math.pow(x - mean, 2)).reduce((a, b) => a + b, 0) / numericData.length);
    
    return { mean: mean.toFixed(2), std: std.toFixed(2) };
};

const QUESTION_SETS = {
    informedConsent: {
        title: "Informed Consent Responses",
        type: 'frequency',
        questions: {
            consent_ageCheck: "a. Are you 18 years or older?",
            consent_isEmployed: "b. Are you currently employed...?",
            consent_hasParticipated: "c. Have you participated in corporate financial decisions...?",
            consent_consentGiven: "d. I consent to participate in this study.",
        }
    },
    financialLiteracy: {
        title: "Financial Literacy",
        type: 'frequency',
        questions: {
            q1: "i. $100 at 2% for 5 years",
            q2: "ii. Savings at 1% vs. inflation at 2%",
            q3: "iii. Single stock vs. mutual fund safety",
            q4: "iv. Chance of 1 in 100 as percentage",
        }
    },
    comprehensionChecks: {
        title: "Comprehension Checks",
        type: 'frequency',
        questions: {
            q1: "a. What is the name of the Organization?",
            q2: "b. What was the approximate time horizon?",
        }
    },
    manipulationChecks: {
        title: "Manipulation Checks",
        type: 'frequency',
        questions: {
            feltHuman: "a. The source of the advisory felt human.",
            feltAlgorithm: "b. The source of the advisory felt generated by an algorithm.",
            sourceAttribution: "c. Who produced the advisory you just read?",
        }
    },
    objectiveChoice: {
        title: "Decision-Making Task: Objective Choice",
        type: 'frequency',
        questions: {
            objectiveChoice: "a. Which investment option do you recommend?",
        }
    },
    subjectiveDQ: {
        title: "Decision-Making Task: Subjective Quality",
        type: 'mean',
        questions: {
            confidence: "b-i. I am confident that the choice I selected is the right decision...",
            informed: "b-ii. I feel adequately informed to make this decision.",
            clearBasis: "b-iii. The advisory and materials provided a clear basis for making the decision.",
            satisfied: "b-iv. I am satisfied with the decision I made based on the advisory.",
        }
    },
    advisoryCredibility: {
        title: "Advisory Credibility (CR)",
        type: 'mean',
        questions: {
          q1: 'i. The advisory source is honest.',
          q2: 'ii. The advisory source is trustworthy.',
          q3: 'iii. The advisory source is sincere.',
          q4: 'iv. The advisory source is competent.',
          q5: 'v. The advisory source is knowledgeable.',
          q6: 'vi. The advisory source is an expert.',
          q7: 'vii. The advisory source cares about our organization’s best interests.',
          q8: 'viii. The advisory source has our organization’s welfare at heart.',
          q9: 'ix. The advisory source is concerned about our organization.',
        },
    },
    psychologicalDistance: {
        title: "Psychological Distance (PD)",
        type: 'mean',
        questions: {
            q1: 'i. The scenario described felt distant in time for our organization.',
            q2: 'ii. The advisory felt socially distant from stakeholders in our organization (e.g., it did not feel written for people like us).',
            q3: 'iii. The scenario described felt geographically or contextually far from our organization’s operations.',
            q4: 'iv. The events described in the scenario felt unlikely to occur for our organization.',
        },
    },
    linguisticAbstractness: {
        title: "Linguistic Abstractness (LA)",
        type: 'mean',
        questions: {
            q1: 'i. The language used in the advisory was abstract and high-level.',
            q2: 'ii. The advisory used general descriptions rather than specific, actionable steps.',
            q3: 'iii. I had difficulty forming a clear, concrete mental picture of the recommended actions.',
            q4: 'iv. The wording focused on broad principles rather than concrete procedures.',
        },
    },
    outcomeFraming: {
        title: "Outcome Framing (OF)",
        type: 'mean',
        questions: {
            q1: "i. The advisory emphasized potential gains...",
            q2: "ii. The advisory emphasized potential losses...",
            q3: "iii. The advisory focused on probabilities and uncertainty.",
            q4: "iv. The advisory focused on certain guaranteed outcomes.",
        }
    },
    riskTolerance: {
        title: "Risk Tolerance (RT)",
        type: 'mean',
        questions: {
            q1: 'i. Investing 10% in a single high growth ETF.',
            q2: 'ii. Investing 10% in a new, unproven venture.',
            q3: 'iii. Allocating a meaningful portion to speculative equities.',
            q4: 'iv. Investing in a diversified mutual fund that may decline.',
            q5: 'v. Placing funds in government securities to preserve capital.',
        }
    },
    roleAndExperience: {
        title: "Demographics: Role & Experience",
        type: 'frequency',
        questions: {
            q1: "Role Level",
            q2: "Primary Functional Area",
            q3: "Involvement in Financial Decision-Making",
            q4: "Years of Experience (Corporate Financial Decisions)",
            q5: "Years Relying on Advisory Services",
        },
    },
    organizationalProfile: {
        title: "Demographics: Organizational Profile",
        type: 'frequency',
        questions: {
            q1: "Primary Industry",
            q2: "Annual Revenue",
            q3: "Number of Employees",
            q4: "Ownership Structure",
            q5: "Appetite for Financial Risk",
            q6: "Formal Investment Policy",
            q7: "Headquarters country",
        }
    },
};

export default function DescriptiveStatisticsAccordion({ sessions }: DescriptiveStatsProps) {
    
    const stats = useMemo(() => {
        if (!sessions) return {};

        const allStats: Record<string, any> = {
            informedConsent: Object.fromEntries(Object.keys(QUESTION_SETS.informedConsent.questions).map(key => [
                key, calculateFrequency(sessions.map(s => s[key as keyof SessionData]))
            ])),
            financialLiteracy: Object.fromEntries(Object.keys(QUESTION_SETS.financialLiteracy.questions).map(key => [
                key, calculateFrequency(sessions.map(s => s.initialAssessments?.financialLiteracy?.[key as keyof typeof s.initialAssessments.financialLiteracy]))
            ])),
            comprehensionChecks: Object.fromEntries(Object.keys(QUESTION_SETS.comprehensionChecks.questions).map(key => [
                key, calculateFrequency(sessions.map(s => s.comprehension?.[key as keyof typeof s.comprehension]))
            ])),
            manipulationChecks: Object.fromEntries(Object.keys(QUESTION_SETS.manipulationChecks.questions).map(key => [
                key, calculateFrequency(sessions.map(s => s.manipulationChecks?.[key as keyof typeof s.manipulationChecks]))
            ])),
            objectiveChoice: {
                objectiveChoice: calculateFrequency(sessions.map(s => s.objectiveChoice))
            },
            subjectiveDQ: Object.fromEntries(Object.keys(QUESTION_SETS.subjectiveDQ.questions).map(key => [
                key, calculateMeanStd(sessions.map(s => s.subjectiveDQ?.[key as keyof typeof s.subjectiveDQ]))
            ])),
            advisoryCredibility: Object.fromEntries(Object.keys(QUESTION_SETS.advisoryCredibility.questions).map(key => [
                key, calculateMeanStd(sessions.map(s => s.mediators?.advisoryCredibility?.[key as keyof typeof s.mediators.advisoryCredibility]))
            ])),
            psychologicalDistance: Object.fromEntries(Object.keys(QUESTION_SETS.psychologicalDistance.questions).map(key => [
                key, calculateMeanStd(sessions.map(s => s.mediators?.psychologicalDistance?.[key as keyof typeof s.mediators.psychologicalDistance]))
            ])),
            linguisticAbstractness: Object.fromEntries(Object.keys(QUESTION_SETS.linguisticAbstractness.questions).map(key => [
                key, calculateMeanStd(sessions.map(s => s.mediators?.linguisticAbstractness?.[key as keyof typeof s.mediators.linguisticAbstractness]))
            ])),
            outcomeFraming: Object.fromEntries(Object.keys(QUESTION_SETS.outcomeFraming.questions).map(key => [
                key, calculateMeanStd(sessions.map(s => s.mediators?.outcomeFraming?.[key as keyof typeof s.mediators.outcomeFraming]))
            ])),
            riskTolerance: Object.fromEntries(Object.keys(QUESTION_SETS.riskTolerance.questions).map(key => [
                key, calculateMeanStd(sessions.map(s => s.controls?.riskTolerance?.[key as keyof typeof s.controls.riskTolerance]))
            ])),
            roleAndExperience: Object.fromEntries(Object.keys(QUESTION_SETS.roleAndExperience.questions).map(key => [
                key, calculateFrequency(sessions.map(s => s.initialAssessments?.roleAndExperience?.[key as keyof typeof s.initialAssessments.roleAndExperience]))
            ])),
            organizationalProfile: Object.fromEntries(Object.keys(QUESTION_SETS.organizationalProfile.questions).map(key => [
                key, calculateFrequency(sessions.map(s => s.initialAssessments?.organizationalProfile?.[key as keyof typeof s.initialAssessments.organizationalProfile]))
            ])),
        };
        
        return allStats;

    }, [sessions]);

    const renderFrequencyTable = (questionSetKey: keyof typeof QUESTION_SETS) => {
        const questionSet = QUESTION_SETS[questionSetKey];
        if (!questionSet) return null;
        
        const dataSet = stats[questionSetKey];
        if (!dataSet || Object.keys(dataSet).length === 0) return <p className="text-muted-foreground">No data available.</p>;

        return (
            <div className="space-y-6">
                {Object.entries(questionSet.questions).map(([key, label]) => {
                    const data = dataSet[key];
                    if (!data || Object.keys(data).length === 0) return <div key={key}><h4 className="font-semibold mb-2">{label as string}</h4><p className="text-muted-foreground">No data available.</p></div>;
                    return (
                        <div key={key}>
                            <h4 className="font-semibold mb-2">{label as string}</h4>
                            <Table>
                                <TableHeader><TableRow><TableHead>Response</TableHead><TableHead className="text-right">Frequency</TableHead><TableHead className="text-right">Percentage</TableHead></TableRow></TableHeader>
                                <TableBody>
                                    {Object.entries(data as Record<string, { count: number; percentage: string }>).sort(([, a], [, b]) => b.count - a.count).map(([response, values]) => (
                                        <TableRow key={response}><TableCell>{response || "N/A"}</TableCell><TableCell className="text-right">{values.count}</TableCell><TableCell className="text-right">{values.percentage}</TableCell></TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        </div>
                    )
                })}
            </div>
        )
    };

    const renderMeanStdTable = (questionSetKey: keyof typeof QUESTION_SETS) => {
        const questionSet = QUESTION_SETS[questionSetKey];
        const data = stats[questionSetKey];
        if (!data) return <p className="text-muted-foreground">No data available.</p>;
        return (
            <Table>
                <TableHeader><TableRow><TableHead>Item</TableHead><TableHead className="text-right">Mean</TableHead><TableHead className="text-right">Std. Dev.</TableHead></TableRow></TableHeader>
                <TableBody>
                    {Object.entries(questionSet.questions).map(([key, label]) => (
                        <TableRow key={key}><TableCell>{label as string}</TableCell><TableCell className="text-right">{data[key].mean}</TableCell><TableCell className="text-right">{data[key].std}</TableCell></TableRow>
                    ))}
                </TableBody>
            </Table>
        );
    };

    if (!sessions || Object.keys(stats).length === 0) {
        return <p className="text-muted-foreground text-center py-8">No session data available to calculate statistics.</p>;
    }

    return (
        <Accordion type="single" collapsible className="w-full">
            {Object.entries(QUESTION_SETS).map(([key, { title, type }]) => (
                <AccordionItem value={key} key={key}>
                    <AccordionTrigger>{title}</AccordionTrigger>
                    <AccordionContent>
                        <Card>
                            <CardContent className="p-6">
                                {type === 'frequency' ? renderFrequencyTable(key as keyof typeof QUESTION_SETS)
                                 : renderMeanStdTable(key as keyof typeof QUESTION_SETS)}
                            </CardContent>
                        </Card>
                    </AccordionContent>
                </AccordionItem>
            ))}
        </Accordion>
    );
}

    